let mock = [
  {
    id: 1,
    section: "Recent Compositions",
    name: "Kaleidoscope",
    level: "Original Pop Song",
    instruments: null,
    download: "Kaleidoscope.mp3",
  },
  {
    id: 2,
    section: "Recent Compositions",
    name: "Jasmine in June",
    level: "Original Jazz Tune",
    instruments: null,
    download: "Jasmine in June.mp3",
  },
  {
    id: 3,
    section: "Recent Compositions",
    name: "The Journey",
    level: "Original Piano Solo",
    instruments: null,
    download: "",
  },
  {
    id: 4,
    section: "Arrangements",
    name: "Where Can I Turn for Peace",
    level: "Intermediate",
    instruments: "Piano + Voice/Violin",
    download: "",
  },
  {
    id: 5,
    section: "Arrangements",
    name: "The Light, the Life, and the Hope",
    level: "Intermediate",
    instruments: "Piano Solo",
    download: "",
  },
  {
    id: 6,
    section: "Arrangements",
    name: "I Saw Three Ships / Bring a Torch, Jeanette, Isabella",
    level: null,
    instruments: "Arrangement for Woodwinds, Strings, Harp",
    download: "",
  },
  {
    id: 7,
    section: "Arrangements",
    name: "Loch Lomond",
    level: "Intermediate",
    instruments: "SATB + Piano",
    download: "",
  },
  {
    id: 8,
    section: "Arrangements for Piano Students",
    name: "Ode to Joy",
    level: "Early Beginner",
    instruments: "Piano",
    download: "",
  },
  {
    id: 9,
    section: "Arrangements for Piano Students",
    name: "Deck the Halls",
    level: "Early Beginner",
    instruments: "Piano",
    download: "",
  },
  {
    id: 10,
    section: "Arrangements for Piano Students",
    name: "Man in the Mirror",
    level: "Beginner",
    instruments: "Piano",
    download: "",
  },
  {
    id: 11,
    section: "Arrangements for Piano Students",
    name: "Toreador March",
    level: "Beginner",
    instruments: "Piano",
    download: "",
  },
  {
    id: 12,
    section: "Arrangements for Piano Students",
    name: "Stitches",
    level: "Beginner",
    instruments: "Piano",
    download: "",
  },
  {
    id: 13,
    section: "Arrangements for Piano Students",
    name: "Fool For You",
    level: "Late Beginner",
    instruments: "Piano",
    download: "",
  },
  {
    id: 14,
    section: "Arrangements for Piano Students",
    name: "Trust Fund Baby",
    level: "Late Beginner",
    instruments: "Piano",
    download: "",
  },
];

export default mock;
